package org.jongo.jdbc.connections;

import org.jongo.enums.JDBCDriver;
import org.jongo.jdbc.AbstractJDBCConnection;
import org.jongo.jdbc.JongoJDBCConnection;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Alejandro Ayuso <alejandroayuso@gmail.com>
 */
public class HSQLConnection extends AbstractJDBCConnection implements JongoJDBCConnection{

    private static final Logger l = LoggerFactory.getLogger(HSQLConnection.class);
    
    public HSQLConnection(final String url, final String user, final String password) {
        this.url = url;
        this.username = user;
        this.password = password;
        this.driver = JDBCDriver.HSQLDB;
    }

    @Override
    public void loadDriver() {
        l.debug("Loading HSQLDB Driver " + this.driver.getName());
        try {
            Class.forName(this.driver.getName());
        } catch (ClassNotFoundException ex) {
            l.error("Unable to load driver. Add the HSQLDB Connector jar to the lib folder");
        }
    }

    @Override
    public String getCreateJongoQueryTable() {
        return "CREATE TABLE JongoQuery  ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0 INCREMENT BY 1) PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, query VARCHAR(255) NOT NULL, description VARCHAR(50))";
    }

    @Override
    public String getCreateJongoTableQuery() {
        return "CREATE TABLE JongoTable  ( id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0 INCREMENT BY 1) PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE, customId VARCHAR(10), permits INTEGER)";
    }
}
